services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hack
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: backend
    stdin_open: true
    tty: true
    volumes:
      - ./backend/src:/app
    ports:
      - 5000:5000

volumes:
  postgres_data:
